
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#545054"
blue = "#22BBFF"
cyan = "#33FFFF"
green = "#50fc50"
magenta = "#FF66FF"
red = "#f85450"
white = "#f8fcf8"
yellow = "#f8fc50"

[colors.cursor]
cursor = "#56B6C2"
text = "CellBackground"

[colors.normal]
black = "#000000"
blue = "#0077FF"
cyan = "#33FFFF"
green = "#00a800"
magenta = "#a800a8"
red = "#a80000"
white = "#FFFFFF"
yellow = "#a85400"

[colors.primary]
background = "#001f1f"
foreground = "#f8fcf8"

[colors.selection]
background = "#3e4451"
foreground = "#e0e0e0"
text = "CellForeground"

[font.normal]
family = "Hack"

[scrolling]
history = 10000

[window]
title = "tty"

[hints]
enabled = []

[general]
live_config_reload = true


[mouse]
bindings = [
{ mouse = "Middle", action = "None" },
]

[keyboard]
bindings = [
{ key = "V", mods = "Control|Shift", action = "PasteSelection" },
{ key = "K", mods = "Control|Shift", action = "ClearHistory" },
]
