#!/usr/bin/env bash

packages=$(pacman -Syu --print-format "%f" | \
    grep -vP '(?::: Synchronizing|(?:core|extra) (?:downloading|is up to date))'
)

if [[ -n $packages ]]; then
    echo "New packages available:"
    echo $packages
fi
