#!/usr/bin/env bash


# check if reboot needed
running=$(uname -r | sed 's/-/./g')
kernel=linux
if [[ $running =~ ".lts" ]]; then
    kernel=linux-lts
    running=${running%.l*}
fi
installed=$(pacman -Q $kernel | cut -d' ' -f2 | sed 's/-/./g')
[[ $installed == $running ]] || printf "Reboot required. %s->%s\n" $running $installed


# check for update
packages=$(pacman -Syu --print-format "%f" | \
    grep -vP '(?::: Synchronizing|(?:core|extra) (?:downloading|is up to date))'
    )

if [[ -n $packages ]]; then
    echo "New packages available:"
    for package in $packages; do
                echo $package
    done
else
    echo "Packages up to date"
fi
systemd-cat -t create_motd echo "create_motd completed"
